Sensors-in-Paradise/android-native-xsens

app/build.gradle, app/src/main/java/sensors_in_paradise/sonar/page1/Page1Handler.kt, app/src/main/java/sensors_in_paradise/sonar/page1/SensorAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page1/SyncHandler.kt, app/src/main/java/sensors_in_paradise/sonar/page1/SyncInterface.kt, app/src/main/java/sensors_in_paradise/sonar/page1/XSENSArrayList.kt, app/src/main/java/sensors_in_paradise/sonar/page3/Page3Handler.kt, app/src/main/java/sensors_in_paradise/sonar/page3/PredictionsAdapter.kt, app/src/main/res/drawable/ic_baseline_link_24.xml, app/src/main/res/drawable/ic_baseline_link_off_24.xml, app/src/main/res/drawable/ic_baseline_sync_24.xml, app/src/main/res/layout/connection_fragment.xml, app/src/main/res/layout/sensor_device.xml, config/detekt/detekt.yml
=> 30 connection screen synch sensors functionality

app/src/main/java/sensors_in_paradise/sonar/page2/RecordingDataManager.kt
=> Recordings Not Shown

app/build.gradle, app/src/main/java/sensors_in_paradise/sonar/page1/SensorAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/uploader/FileUploader.kt, build.gradle
The file uploader got stuck while reading the file contents of the file to be uploaded. Now fixed.
=> Fixed issue with filer uploader. Updated gradle

app/src/main/java/sensors_in_paradise/sonar/GlobalValues.kt, app/src/main/java/sensors_in_paradise/sonar/JSONStorage.kt, app/src/main/java/sensors_in_paradise/sonar/page2/ActivitiesAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/Page2Handler.kt, app/src/main/java/sensors_in_paradise/sonar/page2/PersistentStringArrayAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/PersistentStringArrayDialog.kt, app/src/main/java/sensors_in_paradise/sonar/page2/Recording.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingDataManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingMetadataStorage.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingsAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/StringItemStorage.kt, app/src/main/res/layout/capture_fragment.xml, app/src/main/res/layout/recording.xml, app/src/main/res/layout/recording_activity_item.xml
Close #52 
One can now record multiple activities in one recording: Just choose another activity while recording and it will memorize when each label was active. 
Also updated UI layout and added an activities view which shows the activities of the current recording
=> 52 label multipart recordings

app/src/main/java/sensors_in_paradise/sonar/GlobalValues.kt, app/src/main/java/sensors_in_paradise/sonar/JSONStorage.kt, app/src/main/java/sensors_in_paradise/sonar/page2/ActivitiesAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/Page2Handler.kt, app/src/main/java/sensors_in_paradise/sonar/page2/PersistentStringArrayAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/PersistentStringArrayDialog.kt, app/src/main/java/sensors_in_paradise/sonar/page2/Recording.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingDataManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingMetadataStorage.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingsAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/StringItemStorage.kt, app/src/main/res/layout/capture_fragment.xml, app/src/main/res/layout/recording.xml, app/src/main/res/layout/recording_activity_item.xml, app/src/main/res/values/colors.xml
Closes #75 
I implemented the appoach we discussed last monday, i.e. choosing a random timestamp and checking whether it appears in all of the recording files. However, there could be two issues with that approach:
* Choosing a random timestamp from a line in the file requires the app to know how many lines there are. This can only be achieved by iterating over a recording file and counting the lines. On top of that, all the other files need to be iterated over as well to find the timestamp in them. Both might take a while depending on the file sizes.
* As Valentin pointed out, the sensors can become unsynchronized after a while. This approach might not be able to detect this problem in certain cases. I can't think of another solution to this though.
=> 75 Check For Synchronized Sensor Data

app/src/main/java/sensors_in_paradise/sonar/XSENSArrayList.kt, app/src/main/java/sensors_in_paradise/sonar/XSensDotDeviceWithOfflineMetadata.kt, app/src/main/java/sensors_in_paradise/sonar/XSensDotMetadataStorage.kt, app/src/main/java/sensors_in_paradise/sonar/page1/Page1Handler.kt, app/src/main/java/sensors_in_paradise/sonar/page1/SensorAdapter.kt, app/src/main/res/layout/connection_fragment.xml, config/detekt/detekt.yml
=> 89 show labels of disconnected xsens dot devices

app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt
=> Remove Person Reset

app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt
=> Remove Colons From Directory Names

app/src/main/AndroidManifest.xml
=> Lock screen orientation

app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt
Fixes #93.
Error caused by deleting import lines in a previous merge.
=> Fix Wrong Timestamps

app/src/main/java/sensors_in_paradise/sonar/GlobalValues.kt
this PR changes the json storage location if you want to record data please get the newest version in notion under guidelines.
If you want to add new activities after you recorded change the file in notion with appended lines
closes #120
=> change storage location

app/build.gradle, app/google-services.json, app/src/main/java/sensors_in_paradise/sonar/MainActivity.kt, build.gradle
Adds crashlytics so that we have a dashboard where we can track issues and collect stack traces
=> feat: add crashlytics

app/src/main/res/layout/strings_dialog_item.xml
=> make delete buttons equal sized

app/src/main/java/sensors_in_paradise/sonar/page2/Recording.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingDataManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingMetadataStorage.kt
=> Cache Recording States

app/src/main/java/sensors_in_paradise/sonar/page1/Page1Handler.kt, app/src/main/java/sensors_in_paradise/sonar/page2/ActivitiesAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/Page2Handler.kt
Speaks for itself :P
Changed behaviour:
- sensors from different sensor sets no longer block recording
- less than 5 connected sensors no longer block recording
- if a sensor disconnects during recording, the recording is stopped & saved instead of thrown away
Additionally the syncing behaviour should now be more stable.
=> Refactor logging manager

app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/PersistentCategoriesDialog.kt, app/src/main/java/sensors_in_paradise/sonar/page2/PersistentStringArrayDialog.kt
=> Fix Dialog Not Cancelable

app/build.gradle, app/src/main/java/sensors_in_paradise/sonar/page2/ActivitiesAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/PersistentCategoriesAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/page2/PersistentCategoriesDialog.kt, app/src/main/res/layout/recording_activity_item.xml
Closes #129.
Clicking an activity in the activity tab opens a dialog. Selecting an item will relabel the activity.
=> 129 Relabel Activities While Recording (new)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/sensors_in_paradise/sonar/GlobalValues.kt, app/src/main/java/sensors_in_paradise/sonar/PageInterface.kt, app/src/main/java/sensors_in_paradise/sonar/page2/CameraManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt, app/src/main/java/sensors_in_paradise/sonar/page2/Page2Handler.kt, app/src/main/java/sensors_in_paradise/sonar/page2/Recording.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingMetadataStorage.kt, app/src/main/java/sensors_in_paradise/sonar/page2/RecordingsAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/uploader/DavCloudRecordingsUploader.kt, app/src/main/java/sensors_in_paradise/sonar/uploader/RecordingUIItem.kt, app/src/main/java/sensors_in_paradise/sonar/util/PermissionsHelper.kt, app/src/main/java/sensors_in_paradise/sonar/util/PreferencesHelper.kt, app/src/main/java/sensors_in_paradise/sonar/util/dialogs/MessageDialog.kt, app/src/main/java/sensors_in_paradise/sonar/util/dialogs/TextInputDialog.kt, app/src/main/java/sensors_in_paradise/sonar/util/dialogs/VideoDialog.kt, app/src/main/res/layout/capture_fragment.xml, app/src/main/res/layout/recording.xml, app/src/main/res/layout/sensor_device.xml, app/src/main/res/values/arrays.xml, app/src/main/res/xml/root_preferences.xml, build.gradle, config/detekt/detekt.yml
=> 148 display camera feed while recording

app/src/main/java/sensors_in_paradise/sonar/screen_recording/RecordingsAdapter.kt
=> add dialog to approve the removal of recordings

app/src/main/java/sensors_in_paradise/sonar/screen_recording/labels_editor/ItemClickableMotionLayout.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/labels_editor/LabelsEditorDialog.kt, app/src/main/res/layout/label_editor.xml, app/src/main/res/xml/label_editor_carousel_scene.xml
=> Improve flickering and make single label clickable

app/src/main/java/sensors_in_paradise/sonar/IntervalLooper.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/RecordingsAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/labels_editor/IntervalLoopSeeker.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/labels_editor/IntervalLooper.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/labels_editor/LabelsEditorDialog.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/labels_editor/PoseSequenceViewHolder.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/labels_editor/VideoViewHolder.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/labels_editor/VisualSequenceViewHolder.kt, app/src/main/java/sensors_in_paradise/sonar/util/dialogs/VideoDialog.kt, app/src/main/res/layout/label_editor.xml, app/src/main/res/layout/video_dialog.xml
=> 184 video slider with current time

app/src/main/java/sensors_in_paradise/sonar/screen_recording/RecordingDataManager.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/RecordingMetadataStorage.kt, app/src/main/java/sensors_in_paradise/sonar/screen_train/PieChartPopulator.kt, app/src/main/java/sensors_in_paradise/sonar/screen_train/TrainingScreen.kt
Closes #195 
Made pie charts interactive so that they get filtered by use selections
=> Satisfy @konakion

app/src/main/java/sensors_in_paradise/sonar/screen_recording/camera/CameraManager.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/camera/pose_estimation/ImageProcessor.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/camera/pose_estimation/MoveNet.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/camera/pose_estimation/PoseDetector.kt, app/src/main/java/sensors_in_paradise/sonar/util/PreferencesHelper.kt, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/root_preferences.xml
1. Added PE model setting
2. Inverted 'Follow System Theme' Color setting
=> add Setting to select PoseEstimation Model,

app/src/main/java/sensors_in_paradise/sonar/JSONStorage.kt, app/src/main/java/sensors_in_paradise/sonar/uploader/DavCloudRecordingsUploader.kt, app/src/main/java/sensors_in_paradise/sonar/uploader/LocalDavCloudMetadataStorage.kt, app/src/main/java/sensors_in_paradise/sonar/uploader/RecordingsUploaderDialog.kt, app/src/main/java/sensors_in_paradise/sonar/util/PreferencesHelper.kt, app/src/main/res/layout/upload_dialog.xml
=> Implement #140

app/src/main/java/sensors_in_paradise/sonar/screen_recording/RecordingScreen.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/camera/CameraManager.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/camera/pose_estimation/ImageProcessor.kt, app/src/main/java/sensors_in_paradise/sonar/screen_recording/camera/pose_estimation/PoseEstimationStorageManager.kt
A few enhancements are not feasable in the scope of this project, so i put them in 'future work'.
Others were already made in other branches and earlier merges.
1. Save capture resolution  / ratio in csv header
2. Clear last pose estimation skeleton from preview screen after recording
=> 166 mutliple enhancements for the pose estimation

app/build.gradle, app/src/main/java/sensors_in_paradise/sonar/GlobalValues.kt, app/src/main/java/sensors_in_paradise/sonar/screen_connection/SensorAdapter.kt, app/src/main/java/sensors_in_paradise/sonar/screen_data/DataScreen.kt, app/src/main/java/sensors_in_paradise/sonar/uploader/RecordingUIItem.kt, app/src/main/java/sensors_in_paradise/sonar/use_cases/UseCase.kt, app/src/main/java/sensors_in_paradise/sonar/util/dialogs/file_explorer/FileExplorerDialog.kt, app/src/main/java/sensors_in_paradise/sonar/util/dialogs/file_explorer/FileNodeViewHolder.kt, app/src/main/java/sensors_in_paradise/sonar/util/dialogs/file_explorer/FileTreeItem.kt, app/src/main/res/drawable/ic_baseline_keyboard_arrow_right_24.xml, app/src/main/res/layout/data_fragment.xml, app/src/main/res/layout/file_explorer_dialog.xml, app/src/main/res/layout/file_explorer_node.xml, app/src/main/res/values/styles.xml
=> 188 File explorer and 193 sensor color fix

app/build.gradle
I just quickly upgraded the dependencies and made a PR to make sure that CI runs through
=> Upgraded dependencies
